### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by pharpend** [wellsoliver/py-retrosheet#20]
I hate to be pedantic. I would like to use this in my project and I am wondering what the permissions are. By default, I don't believe I can even modify the programs legally. If you're unfamiliar with software licensing, try [ChooseALicense](https://choosealicense.com/)

**Comment by wellsoliver** [comment]
License: Use it wherever you want. Re-sell it. Claim ownership. Make a billion dollars. Have at it.
